### ISSUE TITLE
add_unit needs a timeout

### ISSUE THREAD

**Issue by dpb1** [juju/amulet#113]
00:54:26.592 Traceback (most recent call last):
00:54:26.592   File "/usr/lib/python3/dist-packages/zope/testrunner/runner.py", line 400, in run_layer
00:54:26.592     setup_layer(options, layer, setup_layers)
00:54:26.592   File "/usr/lib/python3/dist-packages/zope/testrunner/runner.py", line 713, in setup_layer
00:54:26.592     layer.setUp()
00:54:26.592   File "/var/jenkins/workspace/charm-your-own-adventure/tests/layers.py", line 68, in setUp
00:54:26.592     cls.environment.set_unit_count("landscape-server", 2)
00:54:26.592   File "/var/jenkins/workspace/charm-your-own-adventure/tests/helpers.py", line 370, in set_unit_count
00:54:26.592     self._deployment.add_unit(service)
00:54:26.592   File "/usr/lib/python3/dist-packages/amulet/deployer.py", line 182, in add_unit
00:54:26.592     self.sentry = Talisman(self.services)
00:54:26.592   File "/usr/lib/python3/dist-packages/amulet/sentry.py", line 202, in __init__
00:54:26.592     status = self.wait_for_status(self.juju_env, services, timeout)
00:54:26.592   File "/usr/lib/python3/dist-packages/amulet/sentry.py", line 344, in wait_for_status
00:54:26.592     for i in helpers.timeout_gen(timeout):
00:54:26.592   File "/usr/lib/python3/dist-packages/amulet/helpers.py", line 108, in timeout_gen
00:54:26.592     raise TimeoutError()
00:54:26.592 amulet.helpers.TimeoutError

The add_unit in deployer.py should take an optional timeout which is passed along to Talisman(self.services)

As it is, there is no way to adjust for slower running charms/tests/clouds, etc.

**Comment by dpb1** [comment]
#114
