### ISSUE TITLE
Deploying "to:" machines not working

### ISSUE THREAD

**Issue by galgalesh** [juju/amulet#148]
For some reason, when amulet deploys a bundle, all the machines get stripped from the bundle. This poses a problem when you specify the machines in a manual environment.

The error:

```
~/streaming$ bundletester
cs:~tengu-bot/trusty/modelinfo-0
    charm-proof                                                            PASS
cs:~tengu-bot/trusty/storm-2
    charm-proof                                                            PASS
    charm-proof                                                            PASS
bundle
    charm-proof                                                            PASS
    00-setup                                                               PASS
    11-integration                                                         PASS

PASS: 6 Total: 6 (2.516341 sec)
ubuntu@h-merlijnt4:~/streaming$ nano tests/11-integration 
ubuntu@h-merlijnt4:~/streaming$ bundletester
cs:~tengu-bot/trusty/modelinfo-0
    charm-proof                                                            PASS
cs:~tengu-bot/trusty/storm-2
    charm-proof                                                            PASS
    charm-proof                                                            PASS
bundle
    charm-proof                                                            PASS
    00-setup                                                               PASS
    11-integration                                                         ERROR

------------------------------------------------------------------------------
ERROR: bundle::11-integration
[/tmp/bundletester-thirbD/streaming/tests/11-integration exit 1]
2016-08-02 02:33:05 Starting deployment of merlijnt41
2016-08-02 02:33:05 Service placement to machine not supported worker to lxc:1
2016-08-02 02:33:05 Deployment stopped. run time: 0.25
/usr/lib/python3/dist-packages/path.py:1719: DeprecationWarning: path is deprecated. Use Path instead.
  warnings.warn(msg, DeprecationWarning)
/usr/lib/python3/dist-packages/charmstore/lib.py:105: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.14.144', 35858), raddr=('162.213.33.122', 443)>
  AVAILABLE_INCLUDES).get('Meta')
/usr/lib/python3/dist-packages/charmstore/lib.py:105: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.14.144', 47801), raddr=('162.213.33.121', 443)>
  AVAILABLE_INCLUDES).get('Meta')
/usr/lib/python3/dist-packages/charmstore/lib.py:105: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.14.144', 35860), raddr=('162.213.33.122', 443)>
  AVAILABLE_INCLUDES).get('Meta')
/usr/lib/python3/dist-packages/charmstore/lib.py:105: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.14.144', 47803), raddr=('162.213.33.121', 443)>
  AVAILABLE_INCLUDES).get('Meta')
/usr/lib/python3/dist-packages/charmstore/lib.py:105: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.14.144', 35862), raddr=('162.213.33.122', 443)>
  AVAILABLE_INCLUDES).get('Meta')
E
======================================================================
ERROR: setUpClass (__main__.TestCharm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bundletester-thirbD/streaming/tests/11-integration", line 51, in setUpClass
    cls.deployment.setup(timeout=SECONDS_TO_WAIT)
  File "/usr/lib/python3/dist-packages/amulet/deployer.py", line 668, in setup
    subprocess.check_call(shlex.split(cmd))
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['juju-deployer', '-W', '-c', '/tmp/amulet-juju-deployer-vxk34ppu/deployer-schema.json', '-e', 'merlijnt41', '-t', '1300', 'merlijnt41']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 0 tests in 1.402s

FAILED (errors=1)
Deploying bundle: /tmp/bundletester-thirbD/streaming/bundle.yaml

PASS: 5 ERROR: 1 Total: 6 (3.818765 sec)
```

You can find the complete bundle (tests and bundle code) here: https://github.com/IBCNServices/tengu-charms/tree/a18583f897f8b68c9ebc59d8ff622bc43630acde/bundles/streaming

**Comment by galgalesh** [comment]
As you can see, the schema supplied by amulet to bundledeployer doesn't contain any machines.
```
cat /tmp/amulet-juju-deployer-vxk34ppu/deployer-schema.json
{
  "merlijnt41": {
    "relations": [
      [
        "nimbus",
        "apache-zookeeper"
      ],
      [
        "worker",
        "apache-zookeeper"
      ],
      [
        "nimbus:master",
        "worker:worker"
      ]
    ],
    "services": {
      "modelinfo": {
        "charm": "cs:~tengu-bot/trusty/modelinfo-0",
        "options": {
          "tag": "storm",
          "type": "web-ui"
        },
        "series": "trusty",
        "num_units": 1
      },
      "nimbus": {
        "charm": "cs:~tengu-bot/trusty/storm-2",
        "to": [
          "lxc:0"
        ],
        "series": "trusty",
        "num_units": 1
      },
      "cassandra": {
        "charm": "cs:trusty/cassandra-17",
        "to": [
          "lxc:0"
        ],
        "series": "trusty",
        "num_units": 1
      },
      "apache-zookeeper": {
        "charm": "cs:~tengu-bot/trusty/apache-zookeeper-0",
        "to": [
          "lxc:0"
        ],
        "series": "trusty",
        "num_units": 1
      },
      "worker": {
        "charm": "cs:~tengu-bot/trusty/storm-2",
        "to": [
          "lxc:1"
        ],
        "series": "trusty",
        "num_units": 1
      }
    },
    "series": "trusty"
  }
}
```

**Comment by kwmonroe** [comment]
Raising the heat on this.. We have to resort to unholy measures to get a ./tests/foo.py deployment working.  Eg:

```
        bundle = yaml.safe_load(bun)

        # NB: strip machine ('to') placement out. amulet loses our machine spec
        # somewhere between yaml and json; without that spec, charms specifying
        # machine placement will not deploy. This is ok for now because all
        # charms in this bundle are using 'reset: false' so we'll already
        # have our deployment just the way we want it by the time this test
        # runs. However, it's bad. Somebody tell marco.
        for service, service_config in bundle['services'].items():
            if 'to' in service_config:
                del service_config['to']

        cls.d.load(bundle)
```

As you can see, we're reading yaml from disk, then stripping any `to` placement directives before passing it to `amulet.Deployment().load()`.  This works for us because we use `reset: false` in our `./tests/tests.yaml`, but it's awfully awful.

Just add `machines{}` to the schema in `amulet.Deployment().load()` and we can be great again.
