### ISSUE TITLE
error: flag provided but not defined: -e (testing actions)

### ISSUE THREAD

**Issue by ryan-beisner** [juju/amulet#178]
`juju action -e` isn't a thing for 1.x.  The following commit is causing action tests to fail in our regression gate for 1.25.x:  https://github.com/juju/amulet/commit/b33572a60f1f5c63d49e00c4e32b8a843503dd67

```
DEBUG:runner:2017-03-30 19:32:53,374 run_action WARNING: charmhelpers.contrib.amulet.utils.run_action has been deprecated for amulet.run_action
DEBUG:runner:Traceback (most recent call last):
DEBUG:runner:  File "/tmp/bundletester-PKymcS/nova-cloud-controller/tests/gate-basic-xenial-mitaka", line 24, in <module>
DEBUG:runner:    deployment.run_tests()
DEBUG:runner:  File "/tmp/bundletester-PKymcS/nova-cloud-controller/tests/charmhelpers/contrib/amulet/deployment.py", line 97, in run_tests
DEBUG:runner:    getattr(self, test)()
DEBUG:runner:  File "/tmp/bundletester-PKymcS/nova-cloud-controller/tests/basic_deployment.py", line 874, in test_901_pause_resume
DEBUG:runner:    action_id = u.run_action(self.nova_cc_sentry, "pause")
DEBUG:runner:  File "/tmp/bundletester-PKymcS/nova-cloud-controller/tests/charmhelpers/contrib/amulet/utils.py", line 803, in run_action
DEBUG:runner:    return unit_sentry.run_action(action, action_args=params)
DEBUG:runner:  File "/var/lib/jenkins/checkout/0/nova-cloud-controller/.tox/func27-smoke/local/lib/python2.7/site-packages/amulet/sentry.py", line 110, in run_action
DEBUG:runner:    self.info['unit_name'], action, action_args=action_args)
DEBUG:runner:  File "/var/lib/jenkins/checkout/0/nova-cloud-controller/.tox/func27-smoke/local/lib/python2.7/site-packages/amulet/actions.py", line 50, in run_action
DEBUG:runner:    result = juju(cmd)
DEBUG:runner:  File "/var/lib/jenkins/checkout/0/nova-cloud-controller/.tox/func27-smoke/local/lib/python2.7/site-packages/amulet/helpers.py", line 81, in juju
DEBUG:runner:    "{}".format(args, _as_text(err)))
DEBUG:runner:IOError: juju command failed ['action', '-e', 'osci-lb03', 'do', 'nova-cloud-controller/0', 'pause', '--format', 'json']:
DEBUG:runner:error: flag provided but not defined: -e
DEBUG:runner:
DEBUG:runner:Exit Code: 1
DEBUG:bundletester.utils:Updat
```

**Comment by ryan-beisner** [comment]
I believe the correct command would be:

```juju action do -e FOO stuff```

And not:

```juju action -e FOO do stuff```

**Comment by thedac** [comment]
https://github.com/juju/amulet/pull/179

Tested this with juju 1.x and 2.x
