### ISSUE TITLE
'branch:', doesn't quite work

### ISSUE THREAD

**Issue by dpb1** [juju/amulet#54]
Seems like it is reaching out to the charm store to check on things when I'm actually using 'branch'.  My goal here is to test on utopic without having to have utopic (and vivid, etc) bits in the charm store.

```
dpb@helo:trunk$ tests/10-bundles-test.py
E/usr/lib/python3.4/unittest/suite.py:173: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('10.172.68.236', 44129), raddr=('91.189.92.34', 443)>
  self._addClassOrModuleLevelException(result, e, errorName)

======================================================================
ERROR: setUpClass (__main__.BundleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/amulet/deployer.py", line 39, in fetch
    return super(CharmCache, self).__getitem__(service)
KeyError: 'ubuntu-trusty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/charmworldlib/charm.py", line 158, in _fetch
    revision=revision))
  File "/usr/lib/python3/dist-packages/charmworldlib/api.py", line 18, in get
    return self.fetch_json(endpoint, params, 'get')
  File "/usr/lib/python3/dist-packages/charmworldlib/api.py", line 26, in fetch_json
    raise Exception('Request failed with: %s' % r.status_code)
Exception: Request failed with: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/10-bundles-test.py", line 22, in setUpClass
    d.load(contents)
  File "/usr/lib/python3/dist-packages/amulet/deployer.py", line 83, in load
    constraints=constraints,
  File "/usr/lib/python3/dist-packages/amulet/deployer.py", line 96, in add
    c = self.charm_cache.fetch(service, charm, self.series)
  File "/usr/lib/python3/dist-packages/amulet/deployer.py", line 44, in fetch
    series=series,
  File "/usr/lib/python3/dist-packages/amulet/charm.py", line 28, in get_charm
    return Charm(with_series(charm_path))
  File "/usr/lib/python3/dist-packages/charmworldlib/charm.py", line 131, in __init__
    self._fetch(charm_id)
  File "/usr/lib/python3/dist-packages/charmworldlib/charm.py", line 161, in _fetch
    raise CharmNotFound('API request failed: %s' % str(e))
charmworldlib.charm.CharmNotFound: API request failed: Request failed with: 404

----------------------------------------------------------------------
Ran 0 tests in 0.827s

FAILED (errors=1)
dpb@helo:trunk$ vim tests/bundles.yaml
dpb@helo:trunk$ cat tests/bundles.yaml
landscape-client-test:
  services:
    landscape-client-precise:
      charm: landscape-client
      series: precise

    ubuntu-precise:
      branch: lp:charms/ubuntu
      series: precise
      num_units: 1

    landscape-client-trusty:
      charm: landscape-client
      series: trusty

    ubuntu-trusty:
      branch: lp:charms/ubuntu
      series: trusty
      num_units: 1

  relations:
    - [ "landscape-client-trusty", "ubuntu-trusty" ]
    - [ "landscape-client-precise", "ubuntu-precise" ]
dpb@helo:trunk$
```

**Comment by tvansteenburgh** [comment]
Fixed by 9052016f71e2c5cb79436f9bd4dcea4f8eaf0a0e
